# Database Management Systems - Lab 3
## Sreehari P Sreedhar
CB.SC.I5DAS20032

In [16]:
import os

try:
    os.remove('./Dumps/lab4.db')
except FileNotFoundError:
    pass

In [17]:
import sqlite3

In [18]:
conn = sqlite3.connect('./Dumps/lab4.db')

cur = conn.cursor()

In [19]:
createTable = '''
    BEGIN;

    CREATE TABLE EMP(
        EMPNO INT PRIMARY KEY,
        ENAME VARCHAR(25),
        JOB VARCHAR(20),
        MGR INT,
        SAL NUMBER(6,2),
        DEPTNO INT
        );

    INSERT INTO EMP(EMPNO,ENAME,JOB,MGR,SAL,DEPTNO) VALUES(7369,'SMITH','CLERK',7902,800.00,20);
    INSERT INTO EMP VALUES(7499,'ALLEN','SALESMAN',7698,1600.00,30);
    INSERT INTO EMP VALUES(7521,'WARD','SALESMAN',7698,1250.00,30);
    INSERT INTO EMP VALUES(7566,'JONES','MANAGER',7839,2975.00,20);
    INSERT INTO EMP VALUES(7654,'MARTIN','SALESMAN',7689,1250.00,30);
    INSERT INTO EMP VALUES(7698,'BLAKE','MANAGER',7839,2850.00,30);
    INSERT INTO EMP VALUES(7782,'CLARK','MANAGER',7839,2450.00,10);
    INSERT INTO EMP VALUES(7788,'SCOTT','ANALYST',7566,3000.00,20);
    INSERT INTO EMP VALUES(7839,'KING','PRESIDENT',NULL,5000.00,10);
    INSERT INTO EMP VALUES(7844,'TURNER','SALESMAN',7698,1500.00,30);
    INSERT INTO EMP VALUES(7876,'ADAMS','CLERK',7788,1100.00,20);
    INSERT INTO EMP VALUES(7900,'JAMES','CLERK',7698,950.00,30);
    INSERT INTO EMP VALUES(7902,'FORD','ANALYST',7566,3000.00,20);
    INSERT INTO EMP VALUES(7934,'MILLER','CLERK',7782,1300.00,10);

    COMMIT;
'''

cur.executescript(createTable)

1.	Find the info of employee getting salary greater than empid: 7566.

In [20]:
cur.execute('SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE EMPNO = 7566)').fetchall()

[(7788, 'SCOTT', 'ANALYST', 7566, 3000, 20),
 (7839, 'KING', 'PRESIDENT', None, 5000, 10),
 (7902, 'FORD', 'ANALYST', 7566, 3000, 20)]

2.  Display the employees whose job title is the same as that of employee 7369.

In [21]:
cur.execute('SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE EMPNO = 7369)').fetchall()

[(7369, 'SMITH', 'CLERK', 7902, 800, 20),
 (7876, 'ADAMS', 'CLERK', 7788, 1100, 20),
 (7900, 'JAMES', 'CLERK', 7698, 950, 30),
 (7934, 'MILLER', 'CLERK', 7782, 1300, 10)]

3.  Display employees whose job title is the same as that of employee 7369 and whose salary is greater than that of employee 7876.

In [22]:
cur.execute('SELECT * FROM EMP WHERE (JOB = (SELECT JOB FROM EMP WHERE EMPNO = 7369) AND SAL > (SELECT SAL FROM EMP WHERE EMPNO = 7876))').fetchall()

[(7934, 'MILLER', 'CLERK', 7782, 1300, 10)]

4.  Display the employee name, job title, deptno and salary of all employees whose works in the same dept as PRESIDENT.

In [23]:
cur.execute("SELECT ENAME, JOB, DEPTNO, SAL FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE JOB = 'PRESIDENT')").fetchall()

[('CLARK', 'MANAGER', 10, 2450),
 ('KING', 'PRESIDENT', 10, 5000),
 ('MILLER', 'CLERK', 10, 1300)]

5.  Display all the departments(deptno) that having a minimum salary greater than that of department 20.

In [24]:
cur.execute("SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING MIN(SAL) > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 20)").fetchall()

[(10,), (30,)]

6.  Display the employees whose salary is less than any clerk and who are not clerks.

In [28]:
cur.execute("SELECT * FROM EMP WHERE (SAL < (SELECT MAX(SAL) FROM EMP WHERE JOB = 'CLERK') AND JOB != 'CLERK')").fetchall()

[(7521, 'WARD', 'SALESMAN', 7698, 1250, 30),
 (7654, 'MARTIN', 'SALESMAN', 7689, 1250, 30)]

7.  Display the employees whose salary is greater than the average salaries of all the departments.

In [29]:
cur.execute("SELECT * FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO)").fetchall()

[(7566, 'JONES', 'MANAGER', 7839, 2975, 20),
 (7788, 'SCOTT', 'ANALYST', 7566, 3000, 20),
 (7839, 'KING', 'PRESIDENT', None, 5000, 10),
 (7902, 'FORD', 'ANALYST', 7566, 3000, 20)]

8.  Display the emp info for the job sectors clerk and saleman: use operator 'in'.

In [30]:
cur.execute("SELECT * FROM EMP WHERE EMPNO IN (SELECT EMPNO FROM EMP WHERE (JOB = 'CLERK' OR JOB = 'SALESMAN'))").fetchall()

[(7369, 'SMITH', 'CLERK', 7902, 800, 20),
 (7499, 'ALLEN', 'SALESMAN', 7698, 1600, 30),
 (7521, 'WARD', 'SALESMAN', 7698, 1250, 30),
 (7654, 'MARTIN', 'SALESMAN', 7689, 1250, 30),
 (7844, 'TURNER', 'SALESMAN', 7698, 1500, 30),
 (7876, 'ADAMS', 'CLERK', 7788, 1100, 20),
 (7900, 'JAMES', 'CLERK', 7698, 950, 30),
 (7934, 'MILLER', 'CLERK', 7782, 1300, 10)]

9.  Display the emp info for the job sectors not as analyst, manager: use operator 'not in'.

In [31]:
cur.execute("SELECT * FROM EMP WHERE EMPNO NOT IN (SELECT EMPNO FROM EMP WHERE (JOB = 'ANALYST' OR JOB = 'MANAGER'))").fetchall()

[(7369, 'SMITH', 'CLERK', 7902, 800, 20),
 (7499, 'ALLEN', 'SALESMAN', 7698, 1600, 30),
 (7521, 'WARD', 'SALESMAN', 7698, 1250, 30),
 (7654, 'MARTIN', 'SALESMAN', 7689, 1250, 30),
 (7839, 'KING', 'PRESIDENT', None, 5000, 10),
 (7844, 'TURNER', 'SALESMAN', 7698, 1500, 30),
 (7876, 'ADAMS', 'CLERK', 7788, 1100, 20),
 (7900, 'JAMES', 'CLERK', 7698, 950, 30),
 (7934, 'MILLER', 'CLERK', 7782, 1300, 10)]

10.  Write a query to display employee's name and department number of all employees in department 10 and 30 in alphabetical order by name.


In [33]:
cur.execute("SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO IN (10, 30) ORDER BY ENAME").fetchall()

[('ALLEN', 30),
 ('BLAKE', 30),
 ('CLARK', 10),
 ('JAMES', 30),
 ('KING', 10),
 ('MARTIN', 30),
 ('MILLER', 10),
 ('TURNER', 30),
 ('WARD', 30)]

In [34]:
conn.commit()
conn.close()